### ISSUE TITLE
User Story 2 - display information about radiation unit

### ISSUE THREAD

**Issue by sirtobiwan** [sirtobiwan/Capstone-Project-Solar-Calculator#3]
## Value proposition

As a user
I want to get more information about the radiation unit
So that I can understand the data

## Description

![Bildschirm­foto 2023-04-25 um 17 37 32](https://user-images.githubusercontent.com/125971942/234329486-7ed7c3c6-b4ff-4fdf-bfd9-f54d41841762.png)

## Acceptance criteria

- [ ] when click on "radiation in ghi" more information will be displayed about it.

## Tasks

- [ ] create a branch 
- [ ] create a component
- [ ] when click on "*radiation in ghi" open a new window with the following information incl. a pciture: "Global Horizontal Irradiance (GHI) is the total solar radiation incident on a horizontal surface. It is the sum of Direct Normal Irradiance (DNI), Diffuse Horizontal Irradiance, and ground-reflected radiation"

**Comment by t0bbl** [comment]
looks good
